# Generated by Django 5.0.7 on 2024-08-25 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
        ('bot', '0008_telegramchatinfo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='telegram_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='django_user', to='bot.telegramuser'),
        ),
    ]
