# Generated by Django 5.0.7 on 2024-07-27 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_verse', '0002_page_post_page_telegraminfo_verse_page_verse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramInfo',
        ),
    ]
