# Generated by Django 5.0.7 on 2024-08-06 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_telegramchatinfo_delete_telegraminfo'),
        ('user_verse', '0004_remove_post_page_remove_verse_creator_blog_post_blog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='channel',
        ),
        migrations.AddField(
            model_name='post',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='bot.telegramchatinfo'),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
    ]
