# Generated by Django 5.0.7 on 2024-08-07 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_verse', '0005_remove_post_channel_post_chat_delete_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
