# Generated by Django 5.0.7 on 2024-09-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_verse', '0010_alter_post_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='telegram_message_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
