# Generated by Django 5.0.7 on 2024-07-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True)),
                ('chat_name', models.CharField(max_length=256)),
                ('chat_type', models.CharField(max_length=128)),
            ],
        ),
    ]
