# Generated by Django 5.0.7 on 2024-07-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegraminfo',
            old_name='chat_name',
            new_name='chat_title',
        ),
    ]
