# Generated by Django 5.0.7 on 2024-08-02 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_telegramuser_django_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='django_user',
        ),
    ]
