# Generated by Django 5.0.7 on 2024-08-06 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_remove_telegramuser_django_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChatInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True)),
                ('chat_title', models.CharField(max_length=256)),
                ('chat_type', models.CharField(max_length=128)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.telegramuser')),
            ],
        ),
        migrations.DeleteModel(
            name='TelegramInfo',
        ),
    ]
