# Generated by Django 5.0.7 on 2024-08-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_telegramchatinfo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramchatinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='channel_photos/'),
        ),
    ]
